# Use the .NET 8 SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /workspace

# Copy the C# project file and restore dependencies
#RUN dotnet restore

# Copy the rest of the source code and build the application
#COPY sample/. .
#RUN dotnet publish -c Release -o out
