<?php
// Code generated by cyamli, DO NOT EDIT.

namespace Tests\features;

use \Cyamli\features\CLIHandler;

use \Cyamli\features\Input;
use \Cyamli\features\Input_Sub1;
use \Cyamli\features\Input_Sub1Sub2;
use \Cyamli\features\Input_Sub1Sub2Sub3;

class CLIHandlerMock implements CLIHandler {
    /** @var mixed */
    public $gotInput;
    
    public function Run(Input $input): void {
        $this->gotInput = $input;
    }
    
    public function Run_Sub1(Input_Sub1 $input): void {
        $this->gotInput = $input;
    }
    
    public function Run_Sub1Sub2(Input_Sub1Sub2 $input): void {
        $this->gotInput = $input;
    }
    
    public function Run_Sub1Sub2Sub3(Input_Sub1Sub2Sub3 $input): void {
        $this->gotInput = $input;
    }
    
}
