<?php
// Code generated by cyamli, DO NOT EDIT.

namespace Tests\features;

use PHPUnit\Framework\TestCase;
use \Cyamli\features\Cyamli;
use \Cyamli\features\Input_Sub1;

class Run_Sub1_Test extends TestCase {
    /**
     * @dataProvider provideTestCases
     */
    public function testRun($name, $args, $wantInput) {
        $mock = new CLIHandlerMock();
        Cyamli::Run($mock, $args);
        $got = $mock->gotInput;
        $want = $wantInput;
        
        $this->assertEquals($want->Opt_PropagationOption, $got->Opt_PropagationOption, $name . ": unexpected input for option: -propagation-option");
        
        
    }

    public function provideTestCases() {
        return [
            // command-line-arguments
            [
                'command-line-arguments',
                ["", "sub1", "-propagation-option=0","--",],
                (function() {
                    $input = new Input_Sub1();
                    
                    $input->Opt_PropagationOption = "0";
                    
                    
                    return $input;
                })(),
            ],
            // default-options
            [
                'default-options',
                ["", "sub1", "--",],
                (function() {
                    $input = new Input_Sub1();
                    
                    $input->Opt_PropagationOption = "";
                    
                    
                    return $input;
                })(),
            ],
            // short-options
            [
                'short-options',
                ["", "sub1", "-propagation-option=0","--",],
                (function() {
                    $input = new Input_Sub1();
                    
                    $input->Opt_PropagationOption = "0";
                    
                    
                    return $input;
                })(),
            ],
            // negated-options
            [
                'negated-options',
                ["", "sub1", "-propagation-option=0","--",],
                (function() {
                    $input = new Input_Sub1();
                    
                    $input->Opt_PropagationOption = "0";
                    
                    
                    return $input;
                })(),
            ],
            // variadic-arguments-zero
            [
                'variadic-arguments-zero',
                ["", "sub1", "-propagation-option=0","--",],
                (function() {
                    $input = new Input_Sub1();
                    
                    $input->Opt_PropagationOption = "0";
                    
                    
                    return $input;
                })(),
            ],
            // variadic-arguments-two
            [
                'variadic-arguments-two',
                ["", "sub1", "-propagation-option=0","--",],
                (function() {
                    $input = new Input_Sub1();
                    
                    $input->Opt_PropagationOption = "0";
                    
                    
                    return $input;
                })(),
            ],
        ];
    }
}

