<?php
// Code generated by cyamli, DO NOT EDIT.

namespace Cyamli\demo;

/**
 * Interface CLIHandler
 */
interface CLIHandler
{
    /**
     * @param Input $input
     */
    public function Run(Input $input): void;
    /**
     * @param Input_Data $input
     */
    public function Run_Data(Input_Data $input): void;
    /**
     * @param Input_Schema $input
     */
    public function Run_Schema(Input_Schema $input): void;
    /**
     * @param Input_Tables $input
     */
    public function Run_Tables(Input_Tables $input): void;
}
