#!/bin/sh
# Code generated by go run ./cli-test/internal/gen-testcases/... DO NOT EDIT!

run_test() {
    message=$1
    want=$2
    entrypoint=$3
    shift 3
    got=$( ${entrypoint} $@ )

    if [ "${got}" = "${want}" ]; then
        echo "OK: ${message}"
    else
        echo "NG: ${message}"
        echo "  execution: ${entrypoint} $@"
        echo "  want:      '${want}'"
        echo "  got:       '${got}'"
    fi
}


run_test 'subcommand should handle positional arguments with zero variadic arguments' \
    'sub_123_true_abc_' \
    dart main.dart sub 123 true abc

run_test 'subcommand should handle positional arguments with multiple variadic arguments' \
    'sub_123_true_abc_x,y,z,w' \
    dart main.dart sub 123 true abc x y z w

