<?php
// Code generated by cyamli, DO NOT EDIT.

namespace Tests\demo;

use PHPUnit\Framework\TestCase;
use \Cyamli\demo\Cyamli;
use \Cyamli\demo\Input_Data;

class Run_Data_Test extends TestCase {
    /**
     * @dataProvider provideTestCases
     */
    public function testRun($name, $args, $wantInput) {
        $mock = new CLIHandlerMock();
        Cyamli::Run($mock, $args);
        $got = $mock->gotInput;
        $want = $wantInput;
        
        $this->assertEquals($want->Opt_Config, $got->Opt_Config, $name . ": unexpected input for option: -config");
        
        $this->assertEquals($want->Opt_Where, $got->Opt_Where, $name . ": unexpected input for option: -where");
        
        
        $this->assertEquals($want->Arg_Table, $got->Arg_Table, $name . ": unexpected input for argument: table");
        
    }

    public function provideTestCases() {
        return [
            // command-line-arguments
            [
                'command-line-arguments',
                ["", "data", "-config=0","-where=0","--","0",],
                (function() {
                    $input = new Input_Data();
                    
                    $input->Opt_Config = "0";
                    
                    $input->Opt_Where = "0";
                    
                    
                    $input->Arg_Table = "0";
                    
                    return $input;
                })(),
            ],
            // default-options
            [
                'default-options',
                ["", "data", "--","0",],
                (function() {
                    $input = new Input_Data();
                    
                    $input->Opt_Config = "";
                    
                    $input->Opt_Where = "";
                    
                    
                    $input->Arg_Table = "0";
                    
                    return $input;
                })(),
            ],
            // short-options
            [
                'short-options',
                ["", "data", "-config=0","-where=0","--","0",],
                (function() {
                    $input = new Input_Data();
                    
                    $input->Opt_Config = "0";
                    
                    $input->Opt_Where = "0";
                    
                    
                    $input->Arg_Table = "0";
                    
                    return $input;
                })(),
            ],
            // negated-options
            [
                'negated-options',
                ["", "data", "-config=0","-where=0","--","0",],
                (function() {
                    $input = new Input_Data();
                    
                    $input->Opt_Config = "0";
                    
                    $input->Opt_Where = "0";
                    
                    
                    $input->Arg_Table = "0";
                    
                    return $input;
                })(),
            ],
            // variadic-arguments-zero
            [
                'variadic-arguments-zero',
                ["", "data", "-config=0","-where=0","--","0",],
                (function() {
                    $input = new Input_Data();
                    
                    $input->Opt_Config = "0";
                    
                    $input->Opt_Where = "0";
                    
                    
                    $input->Arg_Table = "0";
                    
                    return $input;
                })(),
            ],
            // variadic-arguments-two
            [
                'variadic-arguments-two',
                ["", "data", "-config=0","-where=0","--","0",],
                (function() {
                    $input = new Input_Data();
                    
                    $input->Opt_Config = "0";
                    
                    $input->Opt_Where = "0";
                    
                    
                    $input->Arg_Table = "0";
                    
                    return $input;
                })(),
            ],
        ];
    }
}

