<?php
// Code generated by cyamli, DO NOT EDIT.

namespace Cyamli\cyamli;

/**
 * Interface CLIHandler
 */
interface CLIHandler
{
    /**
     * @param Input $input
     */
    public function Run(Input $input): void;
    /**
     * @param Input_Generate $input
     */
    public function Run_Generate(Input_Generate $input): void;
    /**
     * @param Input_GenerateDart3 $input
     */
    public function Run_GenerateDart3(Input_GenerateDart3 $input): void;
    /**
     * @param Input_GenerateDocs $input
     */
    public function Run_GenerateDocs(Input_GenerateDocs $input): void;
    /**
     * @param Input_GenerateGolang $input
     */
    public function Run_GenerateGolang(Input_GenerateGolang $input): void;
    /**
     * @param Input_GenerateKotlin $input
     */
    public function Run_GenerateKotlin(Input_GenerateKotlin $input): void;
    /**
     * @param Input_GeneratePython3 $input
     */
    public function Run_GeneratePython3(Input_GeneratePython3 $input): void;
    /**
     * @param Input_GenerateTypescript $input
     */
    public function Run_GenerateTypescript(Input_GenerateTypescript $input): void;
    /**
     * @param Input_Version $input
     */
    public function Run_Version(Input_Version $input): void;
}
