name: Deploy
on:
  release:
    types: [published]

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        env:
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
        run: |
          cd docker
          docker buildx create --use --name=multiplatformbuild
          docker buildx build \
            --platform 'linux/amd64,linux/arm64' \
            --tag ghcr.io/jumpaku/cyamli:latest \
            --tag ghcr.io/jumpaku/cyamli:${GITHUB_REF_NAME} \
            --build-arg CYAMLI_VERSION=${GITHUB_REF_NAME} \
            --push \
            .

  deploy-executable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["darwin", "linux", "windows"]
        goarch: ["amd64", "arm64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      - name: Build and Upload Executable Binary Files
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go build -o "cyamli-${GOOS}-${GOARCH}" -ldflags "-s -w" -trimpath　./v2/cmd/cyamli
          zip "cyamli-${GOOS}-${GOARCH}.zip" "cyamli-${GOOS}-${GOARCH}"
          gh release upload --clobber "${GITHUB_REF_NAME}" "cyamli-${GOOS}-${GOARCH}.zip"
          
          
